USE MASTER 
GO
CREATE DATABASE BDJURIDICO
go
Use BDJURIDICO

CREATE TABLE TIPOPESSOA(
 PROIDINT INT IDENTITY(1,1) PRIMARY KEY,
 TIPDescricao VARCHAR (100) 
 ) 
 GO
 

 CREATE TABLE PROCESSO (
 
 PROID INT IDENTITY (1,1) PRIMARY KEY,
 PRORELATO VARCHAR (1000),
 PRODATA DATETIME,
)
GO

CREATE TABLE PESSOA (
PESID INT IDENTITY (1,1) PRIMARY KEY,
PESNOME VARCHAR (100) NOT NULL,
PESCPF  VARCHAR (20) NOT NULL,
PESCNPJ VARCHAR (20),
PESEXO VARCHAR (100) NOT NULL,

)

ALTER TABLE PESSOA
ADD PESTELEFONE VARCHAR(30);

INSERT PESSOA (PESNOME,PESCPF,PESCNPJ,PESEXO)
VALUES ('KETY','05156',  NULL,'INDECISO')

GO
INSERT TIPOPESSOA VALUES ('KETY')
GO
INSERT PROCESSO VALUES ('REGIS MASSA',GetDate())
select * from pessoa
select *from processo
select *from TIPOPESSOA 
insert  pessoa values (1,1,1, GetDate())
insert processo values (1,2,1, GetDate()) 




 CREATE TABLE PESSOAPROCESSO (
  PESID INT NOT NULL,
  PROID INT NOT NULL,
  TIPID INT NOT NULL,
  DATAVINCULO DATETIME
  CONSTRAINT PK_PESSOAPROCESSO PRIMARY KEY (PESID,PROID),

  CONSTRAINT FK_PESSOAPROCESSO_PESSOA FOREIGN KEY (PESID)
  REFERENCES PESSOA (PESID),
  CONSTRAINT FK_PESSOAPROCESSO_PROID FOREIGN KEY (PROID)
  REFERENCES PROCESSO (PROID),
  CONSTRAINT FK_PESSOAPROCESSO_TIPO FOREIGN KEY (TIPID)
  REFERENCES TIPOPESSOA (TIPID),

 )


